# Generated by Django 6.0.6 on 2026-07-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_watchhistory_options_alter_watchlist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
